# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade')),
                ('quadra', models.CharField(max_length=200, verbose_name='quadra')),
                ('endereco', models.CharField(max_length=200, verbose_name='endereco')),
                ('lote', models.CharField(max_length=200, verbose_name='lote')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('id_telefone', models.IntegerField(verbose_name='telefone')),
                ('id_endereco', models.IntegerField(verbose_name='id_endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Pessoa')),
                ('curso', models.CharField(max_length=200, verbose_name='curso')),
                ('nPeriodos', models.IntegerField(verbose_name='nPeriodos')),
                ('nHraPeriodo', models.IntegerField(verbose_name='nHraPeriodo')),
            ],
            bases=('web.pessoa',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.Pessoa')),
                ('curso', models.CharField(max_length=200, verbose_name='curso')),
                ('nAula', models.IntegerField(verbose_name='nPeriodos')),
                ('nHraAula', models.IntegerField(verbose_name='nHraPeriodo')),
            ],
            bases=('web.pessoa',),
        ),
    ]
