# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=11, null=True, verbose_name='numero'),
        ),
    ]
